# k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: dGVjaHZAMTI1Cg==
  POSTGRES_DB: ZW1wbG95ZWVz
